# Generated by Django 4.2.1 on 2023-06-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_name_en_category_name_uk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
